[[redirects]]
from = "/"
to = "https://linktree.com/spatiparty"
status = 301
force = false

[[redirects]]
from = "https://spati.party"
to = "https://linktree.com/spatiparty"
status = 301
force = false